### ISSUE TITLE
TypeError: useVuelidate is not a function

### ISSUE THREAD

**Issue by lautiamkok** [vuelidate/vuelidate#1056]
You will get the following error during the build process with [Vite SSG](https://github.com/antfu/vite-ssg):

```
TypeError: useVuelidate is not a function
    at setup (file:///home/.../.vite-ssg-temp/main.mjs:3556:16)
    at _sfc_main$A.setup (file:///home/.../.vite-ssg-temp/main.mjs:3666:25)
    at callWithErrorHandling (/home/.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/home/.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5704:29)
    at setupComponent (/home/.../node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5685:11)
    at renderComponentVNode (/home/.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:195:17)
    at renderVNode (/home/.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:307:22)
    at renderComponentSubTree (/home/.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:272:13)
    at renderComponentVNode (/home/.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:211:16)
    at ssrRenderComponent (/home/.../node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:626:12)
```

In my Vue component:

```
<script setup>
import useVuelidate from '@vuelidate/core'
import {
  required,
  email as isEmail,
  minLength
} from '@vuelidate/validators'

// Dynamic validation schema.
const rules = computed(() => {
  const localRules = {
   //...
  }
  return localRules
})
const v$ = useVuelidate(rules, form)
</script>
```

Any ideas on what should be done for SSG/ SSR?

**Comment by dobromir-hristov** [comment]
Can you try to import as named function?

`import { useVuelidate } from "@vuelidate/core"`

**Comment by lautiamkok** [comment]
@dobromir-hristov thank you! it works now with that!

Perhaps this should be updated on the [documentation](https://vuelidate-next.netlify.app/#getting-started-1)? The example code on the documentation uses it as follows:

```
import useVuelidate from '@vuelidate/core'
import { required, email } from '@vuelidate/validators'
```
