### ISSUE TITLE
bug: useVuelidate detected as a commonJS module

### ISSUE THREAD

**Issue by maxbellec** [vuelidate/vuelidate#1111]
**Describe the bug**
When running a build (`node .output/server/index.mjs`) with nuxt 3 on an app that uses Vuelidate, I get an error that Vuelidate is a common JS module :
```
Named export 'useVuelidate' not found. The requested module '@vuelidate/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

I'm no JS expert, but `vuelidate` looks very much like an ESM module, no idea why it would be detected wrongly. The app runs fine in dev mode.

**Reproduction URL**

Not a JS fiddle, but [the repo](https://github.com/SocieteNumerique/La-Base-frontend/tree/vuelidateBug) is open-source, I hope that's OK.

**To Reproduce**
1. `nuxi build`
2. `node .output/server/index.mjs`
3. get the error

**Expected behavior**
Homepage is shown

**Additional context**
```
Listening on http://localhost:3000/
Named export 'useVuelidate' not found. The requested module '@vuelidate/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@vuelidate/core';
const { useVuelidate } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)  
  at async file://./.output/server/chunks/app/render.mjs:527:24  
  at async renderMiddleware (file://./.output/server/chunks/app/render.mjs:576:20)  
  at async handle (file://./.output/server/node_modules/h3/dist/index.mjs:601:19)
```

**Comment by maxbellec** [comment]
if I use the suggested syntax, i get

```
Listening on http://localhost:3000/
(node:549965) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
Cannot use import statement outside a module
  at Object.compileFunction (node:vm:352:18)  
  at wrapSafe (node:internal/modules/cjs/loader:1027:15)  
  at Module._compile (node:internal/modules/cjs/loader:1063:27)  
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)  
  at Module.load (node:internal/modules/cjs/loader:975:32)  
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)  
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
/home/maxime/repos/moine/frontend/.output/server/node_modules/@vuelidate/core/dist/index.esm.js:1
import { isReactive, isReadonly, computed, unref, ref, watch, reactive, isRef, nextTick, inject, provide, getCurrentInstance, onBeforeMount, onBeforeUnmount } from 'vue-demi';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)

Node.js v17.9.0
```

**Comment by Zehir** [comment]
I have the same issue when building with vite;

```bash
(node:31101) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
/workspaces/app/node_modules/.pnpm/@vuelidate+core@2.0.0-alpha.44_vue@3.2.37/node_modules/@vuelidate/core/dist/index.esm.js:1
import { isReactive, isReadonly, computed, unref, ref, watch, reactive, isRef, nextTick, inject, provide, getCurrentInstance, onBeforeMount, onBeforeUnmount } from 'vue-demi';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async build (file:///workspaces/app/node_modules/.pnpm/vite-ssg@0.20.2_j56m2rfnu3i24smq7nq73m7uzq/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
    at async Object.handler (file:///workspaces/app/node_modules/.pnpm/vite-ssg@0.20.2_j56m2rfnu3i24smq7nq73m7uzq/node_modules/vite-ssg/dist/node/cli.mjs:20:3)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by dobromir-hristov** [comment]
As this looked like a problem in vue-demi. Could you please try again, using latest version of Vuelidate?

**Comment by dobromir-hristov** [comment]
Just tested with a fresh Vue3 project with Vite. No problems.

**Comment by Zehir** [comment]
I have the same error with the lastest version of Vuelidate

```bash
[build:*vite] (node:6948) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
[build:*vite] (Use `node --trace-warnings ...` to show where the warning was created)
[build:*vite] 
[build:*vite] [vite-ssg] An internal error occurred.
[build:*vite] [vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
[build:*vite] /workspaces/sharemyludo/node_modules/.pnpm/@vuelidate+core@2.0.0-alpha.45_vue@3.2.39/node_modules/@vuelidate/core/dist/index.esm.js:1
[build:*vite] import { isReactive, isReadonly, computed, unref, ref, watch, reactive, isRef, nextTick, inject, provide, getCurrentInstance, onBeforeMount, onBeforeUnmount } from 'vue-demi';
[build:*vite] ^^^^^^
[build:*vite] 
[build:*vite] SyntaxError: Cannot use import statement outside a module
[build:*vite]     at Object.compileFunction (node:vm:360:18)
[build:*vite]     at wrapSafe (node:internal/modules/cjs/loader:1055:15)
[build:*vite]     at Module._compile (node:internal/modules/cjs/loader:1090:27)
[build:*vite]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
[build:*vite]     at Module.load (node:internal/modules/cjs/loader:1004:32)
[build:*vite]     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
[build:*vite]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
[build:*vite]     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[build:*vite]     at async Promise.all (index 0)
[build:*vite]     at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
[build:*vite]     at async build (file:///workspaces/sharemyludo/node_modules/.pnpm/vite-ssg@0.20.2_ztwlzfgeodinitvntdesg4ochu/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
[build:*vite]     at async Object.handler (file:///workspaces/sharemyludo/node_modules/.pnpm/vite-ssg@0.20.2_ztwlzfgeodinitvntdesg4ochu/node_modules/vite-ssg/dist/node/cli.mjs:20:3)
[build:*vite]  ELIFECYCLE  Command failed with exit code 1.
[build:*vite] pnpm run build:vite exited with code 1
 ELIFECYCLE  Command failed with exit code 1.
```

Did you have the `ssr.noExternal` setting in your `vide.config.ts` for vuelidate ?

**Comment by dobromir-hristov** [comment]
mmm OK that may be me.. let me change that....

**Comment by dobromir-hristov** [comment]
Some ppl have reported they have the same issue as well - https://github.com/antfu/vite-ssg/issues/280

My old bundling setup (Bili, based on rollup) cannot produce an `.mjs` file, so you will have to do that `"type": "module"` thing they are saying for now, or set `noExternal: ['@vuelidate/core']` maybe...

I dont use those tools on a daily basis so its hard to test em out.

**Comment by Zehir** [comment]
The type:module solution is on the vuelidate/core package.json file. I tried to change it from the node_module folder, it's also work in that case.
Also setting the no external option works too

**Comment by dobromir-hristov** [comment]
Oh well then setting `type: module` wont do.... I will research for a better bundler so that we can have proper `.mjs` files.

I cannot add `type: module` because not all exports we have are modules..

**Comment by Zehir** [comment]
You can use this as base template.
https://github.com/antfu/vitesse

**Comment by awacode21** [comment]
@dobromir-hristov  We are experiencing the same problem and our project should go live monday. Currently this is a blocker. Any workaround? I See there is already a pull request added, can you have a look?

**Comment by awacode21** [comment]
ok so setting

```
ssr: {
            noExternal: ['@vuelidate/core'],
        },
```
        
in vite.config worksaround it for now. My project is full esm, i already have type: module in my package.json, but i still got this error.. only setting the noExternal flag solves it for me for now
