### ISSUE TITLE
helpers.forEach

### ISSUE THREAD

**Issue by charbyte-tech** [vuelidate/vuelidate#1252]
### Make sure that you are familiar with documentation before submitting an issue.

Description:
I’m using Vuelidate to validate an array of objects in a Vue 3 application with TypeScript. I'm trying to apply validations using helpers.forEach on a field that is an array containing nested objects. However, when attempting to render or access the validated data, I get the following error:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at $message (@vuelidate_validators.js:161:44)
    at @vuelidate_core.js:190:57
    at ReactiveEffect.fn (vue.js:1246:13)
    at ReactiveEffect.run (vue.js:435:19)
    at get value (vue.js:1258:107)
    at MutableReactiveHandler.get (vue.js:740:61)
    at JSON.stringify (<anonymous>)
    at toDisplayString (vue.js:256:196)
    at Proxy._sfc_render (MyComponent.vue:74:21)
    at renderComponentRoot (vue.js:7758:17)

Steps to Reproduce:

[Vuelidate 2 - Composition API + Vue 3](https://codesandbox.io/p/sandbox/frosty-hill-t73cgw?workspaceId=52b5c462-aec5-4fda-841f-e8d97f7cf759)

```
// I define the validation rules using helpers.forEach as follows:
const rules = {
  collection: {
    $each: helpers.forEach({
      name: {
        required,
        object: {
          value: {
            required,
          },
        },
      },
    }),
  },
};

//I have the following state defined
const state = {
  collection: [
    {
      name: '',
      object: {
        value: null,
      },
    },
    {
      name: 'bar',
      object: {
        value: 1,
      },
    },
  ],
};

//I apply useVuelidate for validation
const v = useVuelidate(rules, state);
```

**Expected behavior**
When I attempt to access the validations or display the results, the error mentioned above occurs.

**Screenshots**
![image](https://github.com/user-attachments/assets/5b053cf4-70e1-4dc6-bfe7-7afc6966717e)

**Comment by jotwea** [comment]
Facing the same issue on my project. Have you solved it meanwhile @charbyte-tech?

**Comment by martinszeltins** [comment]
Having the same issue here. My solution is to use a flat structure.

![Image](https://github.com/user-attachments/assets/5304becc-56ea-4e05-a7fe-43fc8d1d1ab2)

**Comment by Sambuxc** [comment]
I suspect this won't be fixed since the package owner has fled onto other projects @dobromir-hristov
