### ISSUE TITLE
 Mobile browser Errors on vuelidate alpha.js

### ISSUE THREAD

**Issue by krishdev** [vuelidate/vuelidate#640]
### Recently getting these errors on Mobile browsers(both Android and IOS). Not able to replicate on Desktop. Stack Vue.js Vulidate

```
TypeError: (0 , n(...).regex) is not a function
  at call(./node_modules/vuelidate/lib/validators/alpha.js:10:1)
  at __webpack_require__(webpack/bootstrap:78:1)
  at call(./node_modules/vuelidate/lib/validators/index.js:134:37)
  at __webpack_require__(webpack/bootstrap:78:1)
  at call(./scripts/components/forms/component.date-picker.vue?ff0c:1:36)
  at __webpack_require__(webpack/bootstrap:78:1)
  at Module.<anonymous>(./scripts/main-vue.js:44:1)
  at call(./scripts/main-vue.js:400:28)
  at __webpack_require__(webpack/bootstrap:78:1)
  at Module.<anonymous>(./scripts/static-pages.js:1:1)
  at call(./scripts/static-pages.js:532:143)
  at __webpack_require__(webpack/bootstrap:78:1)
  at call(./scripts/view-specific/view-all-plan-block.js:48:9)
  at __webpack_require__(webpack/bootstrap:78:1)
  at checkDeferredModules(webpack/bootstrap:45:1)
  at checkDeferredModules(webpack/bootstrap:151:1)
  at ? (webpack/bootstrap:151:1)
```
### Sometimes sentry highlights a line that is no were existing in the file

````
exports = module.exports = require("../../../node_modules/css-loader/lib/css-base.js")(false);
`````
Debugged it using xcode but no luck. Any ideas/help to replicate or resolve this would be very useful.

Vuelidate version 0.7.4

**Comment by dobromir-hristov** [comment]
Hey, we have not gotten a report for such an error before. Have you managed to find out the issue?
